### ISSUE TITLE
BUG SPOTTING

### ISSUE THREAD

**Issue by ndg8743** [soapstain22/GourmetServer#30]
![image](https://github.com/soapstain22/GourmetServer/assets/73437724/d380bd25-0359-47cf-8398-be7b3b9ab7d8)

anyone can use chestshop commands to give them stuff

**Comment by positivevibes123** [comment]
Doing research on it but the /chestshop:csgive command can only be used by people who have the Chestshop.admin permission node, which is only supposed to be given to server OPs.

![image](https://github.com/soapstain22/GourmetServer/assets/103326339/5ff1c1fa-8587-47ff-b860-6b121087ec9b)

**Comment by positivevibes123** [comment]
It seems like this could be the issue. Everyone is by default given a permission node that is only meant for ops.

![image](https://github.com/soapstain22/GourmetServer/assets/103326339/af78c0ff-9484-4c18-9fa4-50a90268cf6b)
![image](https://github.com/soapstain22/GourmetServer/assets/103326339/69cba984-154c-455b-8729-bd349d2408a8)

**Comment by positivevibes123** [comment]
Yep that was the problem so this issue is resolved

**Comment by soapstain22** [comment]
>Yep that was the problem so this issue is resolved
tested and confirmed
